<a href="https://colab.research.google.com/github/RajaRajeswariDevi/OIBSIP/blob/main/Prediction_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("Final_Dataset.csv")
df.head()

,age,gender,residence,competative_exams,access_to_internet,study_hours_per_day,has_scholarship,extracurricular_activities,fam_fin_status,health,...,f_job,m_job,alcoholic,additional_tuition,fam_size,fam_relation,prev_percent_1,prev_percent_2,prev_percent_3,TARGET_PREDICTION_PERCENT
0,11,M,H,0.0,0.0,4.0,0,1,3,5,...,0,0,0,1,14,4,73,73.0,67.0,71.0
1,14,F,D,0.0,1.0,1.0,1,0,4,2,...,1,0,0,0,1,2,96,87.0,80.0,87.0
2,21,M,H,1.0,1.0,6.0,0,1,5,3,...,1,1,1,0,15,2,81,78.0,93.0,84.0
3,24,F,H,1.0,0.0,7.0,0,0,4,2,...,1,1,1,1,15,4,77,71.0,88.0,78.0
4,12,F,H,0.0,0.0,5.0,1,0,3,1,...,1,0,0,1,13,3,66,78.0,85.0,76.0

In [ ]:
# Import the pandas module
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("Final_Dataset.csv")

# Print the DataFrame
df.head()

# Get information about the DataFrame
df.info()

# Get descriptive statistics for the DataFrame
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2166 entries, 0 to 2165
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         2166 non-null   object
 1   gender                      2166 non-null   object
 2   residence                   2166 non-null   object
 3   competative_exams           2165 non-null   float64
 4   access_to_internet          2165 non-null   float64
 5   study_hours_per_day         2164 non-null   float64
 6   has_scholarship             2166 non-null   int64
 7   extracurricular_activities  2166 non-null   int64
 8   fam_fin_status              2166 non-null   int64
 9   health                      2166 non-null   int64
 10  location                    2166 non-null   object
 11  f_edu                       2166 non-null   int64
 12  m_edu                       2166 non-null   int64
 13  f_job                       2166 non-null   int64
 14  m_job                       2166 non-null   int64
 15  alcoholic                   2166 non-null   int64
 16  additional_tuition          2166 non-null   int64
 17  fam_size                    2166 non-null   int64
 18  fam_relation                2166 non-null   int64
 19  prev_percent_1              2166 non-null   object
 20  prev_percent_2              2166 non-null   float64
 21  prev_percent_3              2166 non-null   float64
 22  TARGET_PREDICTION_PERCENT   2166 non-null   float64
dtypes: float64(6), int64(12), object(5)
memory usage: 389.3+ KB

,competative_exams,access_to_internet,study_hours_per_day,has_scholarship,extracurricular_activities,fam_fin_status,health,f_edu,m_edu,f_job,m_job,alcoholic,additional_tuition,fam_size,fam_relation,prev_percent_2,prev_percent_3,TARGET_PREDICTION_PERCENT
count,2165.000000,2165.000000,2164.000000,2166.000000,2166.000000,2166.000000,2166.00000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000,2166.000000
mean,0.484527,0.852194,4.202403,0.433518,0.701293,3.299169,3.78855,3.298246,2.870268,0.749307,0.392428,1.128347,0.421976,4.372576,3.892890,78.669423,77.528578,80.289174
std,0.577109,0.472292,2.583184,0.523766,0.665805,1.181876,1.13625,1.321580,1.394238,0.433512,0.488404,1.199368,0.522171,1.713192,1.182074,14.087540,13.508973,12.774079
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,2.000000,0.000000,0.000000,3.000000,3.00000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,71.000000,70.000000,74.000000
50%,0.000000,1.000000,4.000000,0.000000,1.000000,3.000000,4.00000,3.000000,3.000000,1.000000,0.000000,1.000000,0.000000,4.000000,4.000000,81.000000,79.000000,82.000000
75%,1.000000,1.000000,6.000000,1.000000,1.000000,4.000000,5.00000,4.000000,4.000000,1.000000,1.000000,2.000000,1.000000,5.000000,5.000000,90.000000,88.000000,89.000000
max,3.000000,3.000000,22.000000,2.000000,10.000000,5.000000,9.00000,5.000000,5.000000,1.000000,1.000000,5.000000,2.000000,17.000000,5.000000,100.000000,100.000000,99.000000

In [ ]:
df.columns

Index(['age', 'gender', 'residence', 'competative_exams', 'access_to_internet',
       'study_hours_per_day', 'has_scholarship', 'extracurricular_activities',
       'fam_fin_status', 'health', 'location', 'f_edu', 'm_edu', 'f_job',
       'm_job', 'alcoholic', 'additional_tuition', 'fam_size', 'fam_relation',
       'prev_percent_1', 'prev_percent_2', 'prev_percent_3',
       'TARGET_PREDICTION_PERCENT'],
      dtype='object')

In [ ]:
categorical_cols = ['gender', 'residence','location' ]

# Performing one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols)

# Displaying the encoded DataFrame
print(df_encoded.head())

  age  competative_exams  access_to_internet  study_hours_per_day  \
0  11                0.0                 0.0                  4.0
1  14                0.0                 1.0                  1.0
2  21                1.0                 1.0                  6.0
3  24                1.0                 0.0                  7.0
4  12                0.0                 0.0                  5.0

   has_scholarship  extracurricular_activities  fam_fin_status  health  f_edu  \
0                0                           1               3       5      4
1                1                           0               4       2      5
2                0                           1               5       3      3
3                0                           0               4       2      2
4                1                           0               3       1      3

   m_edu  ...  gender_17  gender_18  gender_F  gender_M  gender_MF  \
0      5  ...      False      False     False      True      False
1      0  ...      False      False      True     False      False
2      4  ...      False      False     False      True      False
3      1  ...      False      False      True     False      False
4      3  ...      False      False      True     False      False

   residence_D residence_H  location_R  location_T  location_U
0        False        True        True       False       False
1         True       False       False       False        True
2        False        True       False       False        True
3        False        True       False       False        True
4        False        True        True       False       False

[5 rows x 32 columns]

In [ ]:
df1=df_encoded

In [ ]:
X = df1.drop('TARGET_PREDICTION_PERCENT', axis=1)  # Features
y = df1['TARGET_PREDICTION_PERCENT']               # Target

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
import pandas as pd

# Check for non-numeric columns
non_numeric_cols = X_train.select_dtypes(exclude=["number"]).columns

# Print the non-numeric columns
print(f"Non-numeric columns: {non_numeric_cols}")

Non-numeric columns: Index(['age', 'prev_percent_1', 'gender_15', 'gender_16', 'gender_17',
       'gender_18', 'gender_F', 'gender_M', 'gender_MF', 'residence_D',
       'residence_H', 'location_R', 'location_T', 'location_U'],
      dtype='object')

In [ ]:
# Drop the non-numeric columns
X_train = X_train.drop(non_numeric_cols, axis=1)
X_test = X_test.drop(non_numeric_cols, axis=1)

In [ ]:
# Fit the scaler to the training data
scaler.fit(X_train)

# Transform the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
print(X_test_scaled)

[[ 0.87742972  0.30992667 -0.84408549 ...  0.92974474  0.58059555
   0.48305828]
 [ 0.87742972 -1.83600559 -0.45672813 ... -0.77339422  0.06761485
   0.40403969]
 [-0.83202841  0.30992667  1.48005871 ... -2.47653318 -1.27699472
  -1.73241617]
 ...
 [-0.83202841  0.30992667 -1.23144286 ...  0.92974474  0.86637866
   1.36924806]
 [-0.83202841 -1.83600559  0.70534397 ... -1.6249637  -0.27675381
   0.63075657]
 [ 0.87742972  0.30992667 -0.45672813 ...  0.92974474 -0.13386225
   0.70460572]]
[[ 0.87742972  0.30992667 -0.84408549 ...  0.92974474  0.58059555
   0.48305828]
 [ 0.87742972 -1.83600559 -0.45672813 ... -0.77339422  0.06761485
   0.40403969]
 [-0.83202841  0.30992667  1.48005871 ... -2.47653318 -1.27699472
  -1.73241617]
 ...
 [-0.83202841  0.30992667 -1.23144286 ...  0.92974474  0.86637866
   1.36924806]
 [-0.83202841 -1.83600559  0.70534397 ... -1.6249637  -0.27675381
   0.63075657]
 [ 0.87742972  0.30992667 -0.45672813 ...  0.92974474 -0.13386225
   0.70460572]]

In [ ]:
import pandas as pd

# Read the training data from a CSV file
data = pd.read_csv('Final_Dataset.csv')

# Split the data into two parts (e.g., 80% for training and 20% for testing)
train_data = data.sample(frac=0.8, random_state=42)
test_data = data.drop(train_data.index)

# Save the two parts to new CSV files
train_data.to_csv('train_data.csv', index=False)
test_data.to_csv('test_data.csv', index=False)

In [ ]:
test_data.to_csv('prediction_data.csv', index=False)

In [ ]:
# Assuming the file is named 'data.csv' and is in the same directory as your script
file_path = '.csv'

In [ ]:
import pandas as pd

# Read the test data from a CSV file
test_data = pd.read_csv('/content/test_data.csv')

In [ ]:
print('Test Data:')
print(test_data.head())

Test Data:
  age gender residence  competative_exams  access_to_internet  \
0  14      F         D                0.0                 1.0
1  31      F         H                1.0                 1.0
2  31      F         H                0.0                 1.0
3  26      M         H                0.0                 1.0
4  10      F         H                0.0                 0.0

   study_hours_per_day  has_scholarship  extracurricular_activities  \
0                  1.0                1                           0
1                  1.0                1                           1
2                  3.0                1                           0
3                  4.0                1                           0
4                  4.0                1                           1

   fam_fin_status  health  ... f_job  m_job  alcoholic  additional_tuition  \
0               4       2  ...     1      0          0                   0
1               2       5  ...     0      1          1                   0
2               3       5  ...     1      1          1                   1
3               3       1  ...     0      0          0                   0
4               2       3  ...     0      0          0                   0

   fam_size  fam_relation  prev_percent_1  prev_percent_2  prev_percent_3  \
0         1             2            96.0            87.0            80.0
1         6             5            86.0            87.0            70.0
2         7             3            74.0            74.0            85.0
3         3             3            73.0            85.0            72.0
4        15             1            95.0            93.0            73.0

   TARGET_PREDICTION_PERCENT
0                       87.0
1                       81.0
2                       77.0
3                       76.0
4                       87.0

[5 rows x 23 columns]

In [ ]:
x_test=test_data.drop(columns=["TARGET_PREDICTION_PERCENT"])
Y_test=test_data["TARGET_PREDICTION_PERCENT"]

In [ ]:
categorical_cols=["gender","residence","competative_exams","access_to_internet","has_scholarship","extracurricular_activities","fam_fin_status","location","f_job","m_job","alcoholic"]

In [ ]:
# Import the necessary module
from sklearn.preprocessing import OneHotEncoder

# Create an instance of the OneHotEncoder
encoder = OneHotEncoder(drop="first", sparse=False)

# Fit the encoder on the categorical columns of the test data
X_test_encoded = encoder.fit_transform(test_data[categorical_cols])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
X_test=encoded_df=pd.DataFrame(X_test_encoded,columns=encoder.get_feature_names_out(categorical_cols))

In [ ]:
# Check if the categorical_cols list contains any column names that are not present in the X_test dataframe
missing_columns = set(categorical_cols) - set(X_test.columns)

# If there are any missing columns, raise an error


# If all the column names are correct and present in the X_test dataframe, then the code will run without error

In [ ]:
# Import the necessary module
from sklearn.preprocessing import OneHotEncoder

# Create an instance of the OneHotEncoder
encoder = OneHotEncoder(drop="first", sparse=False)

# Fit the encoder on the categorical columns of the test data
X_test_encoded = encoder.fit_transform(test_data[categorical_cols])

# Create a DataFrame with the encoded features
encoded_df = pd.DataFrame(X_test_encoded, columns=encoder.get_feature_names_out(categorical_cols))

# Check if the categorical_cols list contains any column names that are not present in the X_test dataframe
missing_columns = set(categorical_cols) - set(X_test.columns)

# If there are any missing columns, raise an error

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
print("Pre-Processed Test Data:")
print(X_test.head())

Pre-Processed Test Data:
   gender_16  gender_17  gender_F  gender_M  residence_H  \
0        0.0        0.0       1.0       0.0          0.0
1        0.0        0.0       1.0       0.0          1.0
2        0.0        0.0       1.0       0.0          1.0
3        0.0        0.0       0.0       1.0          1.0
4        0.0        0.0       1.0       0.0          1.0

   competative_exams_1.0  competative_exams_2.0  competative_exams_3.0  \
0                    0.0                    0.0                    0.0
1                    1.0                    0.0                    0.0
2                    0.0                    0.0                    0.0
3                    0.0                    0.0                    0.0
4                    0.0                    0.0                    0.0

   access_to_internet_1.0  access_to_internet_2.0  ...  fam_fin_status_4  \
0                     1.0                     0.0  ...               1.0
1                     1.0                     0.0  ...               0.0
2                     1.0                     0.0  ...               0.0
3                     1.0                     0.0  ...               0.0
4                     0.0                     0.0  ...               0.0

   fam_fin_status_5  location_U  f_job_1  m_job_1  alcoholic_1  alcoholic_2  \
0               0.0         1.0      1.0      0.0          0.0          0.0
1               0.0         0.0      0.0      1.0          1.0          0.0
2               0.0         0.0      1.0      1.0          1.0          0.0
3               0.0         1.0      0.0      0.0          0.0          0.0
4               0.0         0.0      0.0      0.0          0.0          0.0

   alcoholic_3  alcoholic_4  alcoholic_5
0          0.0          0.0          0.0
1          0.0          0.0          0.0
2          0.0          0.0          0.0
3          0.0          0.0          0.0
4          0.0          0.0          0.0

[5 rows x 30 columns]

In [ ]:
file_path = '.csv'

In [ ]:
print(test_data_file)

path_to_your_test_data_file.txt

In [ ]:
# Check if the file path is correct
print(test_data_file)

prediction data